In [97]:
# The code is written by Jawwad Shadman Siddique
# Importing Libraries

import pandas as pd
import os
import datetime
import matplotlib.pyplot as plt
import math as mt
import statistics as st
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)

In [66]:
# Checking the working directory
os.getcwd()

'C:\\Users\\USER\\CE_5333\\Assignment 02'

In [67]:
# Reading the Data

a = pd.read_csv('HoustonAQIinp.csv')

In [68]:
a.head()

,tottime,NOX.ts,OZONE.ts,BARO.ts,RELH.ts,DEWPT.ts,TEMP.ts,SRAD.ts,WSPEED.ts,WDIR.ts
0,1/1/2017 0:00,16.45710,3.99490,1010.83,89.4600,63.0142,66.2158,0.0,1.79924,206.810
1,1/1/2017 1:00,13.92407,2.70302,1010.16,90.7717,62.6108,65.4292,0.0,2.14573,224.387
2,1/1/2017 2:00,11.39104,5.41001,1010.39,91.3017,62.4425,65.0717,0.0,2.57577,202.498
3,1/1/2017 3:00,8.85801,7.62012,1011.24,91.8733,62.5842,65.0408,0.0,1.02421,120.443
4,1/1/2017 4:00,8.29567,4.89723,1011.46,92.2408,62.3417,64.6542,0.0,1.23521,163.555

In [69]:
# Getting the size of the dataframe

a.shape

(26280, 10)

In [ ]:
# To divide the Wind Direction into 4 quadrants
# [0 - 90) (N-E); [90 - 180) (E-S); [180-270) (S-W) and [270 - 360)
# Label as ‘North’, ‘East’, ‘South’ and ‘West’

In [70]:
# Extracting the wind direction column as pandas series
wdir = a['WDIR.ts']
wdir = list(wdir) # converting to list

col_len = len(wdir)

# converting the list elements to int

for i in range(0,col_len,1):
    wdir[i] = float(wdir[i])

In [71]:
len(wdir)

26280

In [74]:
wcat = [] # creating an empty list of strings for wdir category
j = 0 # counter for the list

# Creating a list of wdir category
for i in range(0,col_len,1):
    if wdir[i] >= 0 and wdir[i] < 90:
        wcat.append('North')
    elif wdir[i] >= 90 and wdir[i] < 180:
        wcat.append('East')
    elif wdir[i] >= 180 and wdir[i] < 270:
        wcat.append('South')
    else:
        wcat.append('West')

# converting the wcat list to pandas series

wdircat = pd.Series(wcat)
wdircat

# Adding the series to the dataframe

#new_hr = a.assign(candidates = cand_s)

a['Wind_Direction'] = wdircat
a

,tottime,NOX.ts,OZONE.ts,BARO.ts,RELH.ts,DEWPT.ts,TEMP.ts,SRAD.ts,WSPEED.ts,WDIR.ts,Wind_Direction
0,1/1/2017 0:00,16.45710,3.99490,1010.83,89.4600,63.0142,66.2158,0.0,1.79924,206.8100,South
1,1/1/2017 1:00,13.92407,2.70302,1010.16,90.7717,62.6108,65.4292,0.0,2.14573,224.3870,South
2,1/1/2017 2:00,11.39104,5.41001,1010.39,91.3017,62.4425,65.0717,0.0,2.57577,202.4980,South
3,1/1/2017 3:00,8.85801,7.62012,1011.24,91.8733,62.5842,65.0408,0.0,1.02421,120.4430,East
4,1/1/2017 4:00,8.29567,4.89723,1011.46,92.2408,62.3417,64.6542,0.0,1.23521,163.5550,East
...,...,...,...,...,...,...,...,...,...,...,...
26275,12/31/2019 19:00,32.87450,10.85730,1022.05,42.1867,28.3600,50.6775,0.0,0.36687,209.9460,South
26276,12/31/2019 20:00,59.03800,13.86080,1022.10,47.4883,31.6508,50.9050,0.0,0.48968,311.1580,West
26277,12/31/2019 21:00,66.49460,10.08090,1022.06,53.9117,33.0042,49.0592,0.0,0.33871,97.9240,East
26278,12/31/2019 22:00,100.86900,9.78163,1022.16,59.7658,36.5325,49.9358,0.0,0.78962,28.5749,North
26279,12/31/2019 23:00,113.16000,8.42234,1021.74,59.4658,35.9092,49.4850,0.0,0.80501,82.8669,North

In [ ]:
# To compute the minimum. mean, standard deviation and maximum windspeeds for winds from the 'North'.

In [88]:
# Extracting the dataframe for wind direction 'North'

a2 = a.loc[(a['Wind_Direction'] == 'North')]
a2.head()

# Extracting the wind speed column as pandas series
wspeed = a['WSPEED.ts']
wspeed = list(wspeed) # converting to list

col_len = len(wspeed)

# converting the list elements to int

for i in range(0,col_len,1):
    wspeed[i] = float(wspeed[i])

wspeed

[1.79924,
 2.14573,
 2.57577,
 1.02421,
 1.23521,
 0.82856,
 1.98223,
 1.18919,
 0.99743,
 0.83353,
 1.8678,
 2.44403,
 2.17675,
 1.18101,
 2.4581,
 2.09219,
 2.28836,
 3.66573,
 5.92358,
 5.53552,
 3.86587,
 3.66982,
 3.46413,
 3.49257,
 2.12001,
 2.41624,
 4.05711,
 6.56527,
 9.59097,
 8.39331,
 7.16363,
 8.1172,
 8.78009,
 7.56818,
 2.5295,
 3.30835,
 8.5193,
 8.25215,
 6.41295,
 5.59491,
 6.4121,
 5.43819,
 1.27504,
 1.19671,
 0.82415,
 0.48446,
 0.79432,
 1.15919,
 1.6497,
 0.46537,
 0.52017,
 0.93831,
 2.50317,
 0.93715,
 2.16846,
 1.85066,
 5.49777,
 6.71944,
 8.78642,
 11.4468,
 10.6041,
 8.75113,
 7.85648,
 7.34023,
 7.28735,
 4.12904,
 3.01855,
 9.21935,
 11.5897,
 12.5047,
 10.634,
 9.61068,
 11.5752,
 9.46865,
 10.373,
 10.202,
 7.46726,
 9.49512,
 7.90473,
 8.25987,
 7.62357,
 6.44022,
 6.59626,
 5.9826,
 5.62333,
 4.31334,
 3.99319,
 3.90502,
 3.38554,
 3.5773,
 3.00386,
 3.23874,
 1.09017,
 0.7853,
 1.06383,
 1.40102,
 0.91445,
 1.85773,
 2.69552,
 1.68359,
 2.28457,
 2.74951,
 2.39267,
 1.78975,
 2.86718,
 3.67331,
 4.58974,
 4.65107,
 5.31599,
 3.52364,
 3.49416,
 4.5408,
 4.99558,
 5.45755,
 6.04349,
 8.72763,
 12.0679,
 10.8089,
 10.6719,
 11.0211,
 8.86331,
 9.42945,
 8.88383,
 8.38951,
 10.246,
 11.8422,
 10.088,
 9.30462,
 8.81183,
 8.62141,
 7.92746,
 8.61771,
 9.99616,
 10.4135,
 11.4662,
 11.4889,
 11.47,
 12.6449,
 12.0095,
 12.8983,
 12.1183,
 11.2439,
 12.3687,
 12.3801,
 11.5627,
 10.4727,
 9.05267,
 9.13832,
 9.71222,
 9.16634,
 6.45813,
 7.21496,
 8.42386,
 7.56795,
 7.19878,
 7.98215,
 7.74491,
 8.97377,
 8.41571,
 8.45244,
 7.44104,
 5.68691,
 3.52363,
 2.87388,
 2.11853,
 2.06917,
 1.12889,
 2.01945,
 0.83289,
 0.99738,
 2.58879,
 1.71864,
 0.83763,
 0.41184,
 1.32926,
 0.68833,
 1.35132,
 4.9274,
 7.05511,
 5.64239,
 4.41188,
 5.5752,
 7.50249,
 8.55327,
 7.80574,
 6.53867,
 5.03364,
 4.85191,
 3.96044,
 4.39769,
 4.51974,
 4.24252,
 4.15151,
 4.17592,
 4.1598,
 4.98628,
 4.87813,
 5.42616,
 4.85334,
 4.06525,
 6.51224,
 8.84605,
 9.79305,
 10.5381,
 12.4201,
 8.66201,
 8.20614,
 6.88412,
 4.93958,
 6.62359,
 7.13146,
 6.73473,
 6.68875,
 6.83254,
 6.46954,
 6.26078,
 6.65273,
 6.52272,
 7.95229,
 8.3084,
 7.16873,
 7.44688,
 8.99402,
 8.43534,
 7.37529,
 8.8823,
 10.6871,
 11.5325,
 13.0343,
 13.5164,
 13.8682,
 11.7728,
 9.64954,
 7.57043,
 7.76472,
 6.9458,
 5.28891,
 6.66761,
 6.51426,
 5.97805,
 6.25312,
 4.99702,
 4.94074,
 4.28424,
 5.10577,
 4.94533,
 5.63681,
 6.44163,
 7.75988,
 10.8193,
 13.0597,
 11.4076,
 12.4445,
 13.0334,
 13.3971,
 13.0876,
 10.9745,
 10.0405,
 10.461,
 9.16091,
 9.30122,
 8.73789,
 7.10393,
 6.88197,
 8.82193,
 8.13032,
 7.35862,
 4.87158,
 5.43088,
 5.64333,
 5.57279,
 5.24625,
 6.1056,
 7.72237,
 10.2113,
 8.92772,
 9.10682,
 9.41786,
 8.79846,
 8.97998,
 8.67207,
 8.1613,
 5.66211,
 4.83238,
 4.53411,
 5.23758,
 5.3982,
 6.42395,
 7.58543,
 6.0709,
 6.40062,
 3.69748,
 4.34212,
 4.13544,
 5.17882,
 6.44328,
 7.65975,
 6.89156,
 8.09345,
 9.9548,
 9.26932,
 9.12008,
 9.22759,
 9.05146,
 8.82114,
 7.93274,
 6.00787,
 5.70766,
 5.87816,
 4.64642,
 5.80799,
 5.59915,
 6.34639,
 5.25424,
 4.52019,
 6.65655,
 6.5089,
 5.10978,
 6.30786,
 6.36554,
 6.85462,
 7.07998,
 5.55802,
 6.97611,
 6.84122,
 6.5958,
 7.49688,
 7.23502,
 6.49839,
 4.99421,
 5.35833,
 5.269,
 4.74115,
 2.95296,
 1.51186,
 1.9804,
 3.31241,
 4.34968,
 2.80468,
 4.10848,
 4.0056,
 3.90625,
 3.98002,
 6.19495,
 7.34358,
 7.13779,
 9.279,
 9.07117,
 11.1178,
 11.8579,
 14.1109,
 11.4027,
 10.8251,
 11.2215,
 10.7009,
 10.3634,
 9.91214,
 8.51723,
 7.51129,
 8.9275,
 8.82341,
 4.27788,
 5.08414,
 4.13862,
 4.91716,
 5.91731,
 8.12085,
 8.26756,
 9.91069,
 11.5214,
 12.9098,
 13.0529,
 12.8377,
 11.7253,
 11.2397,
 11.4847,
 10.9564,
 9.09489,
 8.31217,
 5.9586,
 4.902,
 5.16503,
 5.41708,
 5.67347,
 4.64646,
 3.99886,
 3.52387,
 3.47357,
 3.61094,
 4.90446,
 5.64782,
 1.6678,
 7.45031,
 5.34185,
 5.91271,
 7.02999,
 5.97884,
 6.70123,
 7.15572,
 6.65361,
 6.15948,
 6.10749,
 5.6764,
 5.18164,
 5.0871,
 5.11339,
 5.15969,
 4.63813,
 3.94625,
 0.97056,
 2.53635,
 5.93763,
 4.92466,
 1.53945,
 0.54917,
 2.41382,
 4.01776,
 1.90538,
 1.81766,
 4.75196,
 6.3147,
 7.78416,
 4.73121,
 6.51089,
 2.82352,
 2.09509,
 4.44171,
 5.82725,
 6.3791,
 6.04477,
 5.59371,
 5.07387,
 4.42618,
 3.34347,
 1.57044,
 5.28144,
 7.31916,
 4.15097,
 2.44289,
 0.76119,
 4.08913,
 5.60845,
 4.6336,
 4.84472,
 5.5683,
 6.93058,
 6.68326,
 6.43359,
 4.30117,
 3.1976,
 3.53449,
 3.60301,
 2.00859,
 1.29642,
 2.43721,
 2.37448,
 3.3263,
 3.22402,
 3.41751,
 4.68717,
 6.34817,
 4.95846,
 4.33473,
 4.81451,
 6.80071,
 7.10083,
 3.24305,
 2.35615,
 4.01062,
 5.22357,
 3.86632,
 3.05113,
 1.65869,
 1.5074,
 2.38445,
 5.57834,
 5.19145,
 5.30352,
 4.73506,
 3.02284,
 1.47534,
 1.40266,
 2.70105,
 3.82968,
 2.61508,
 2.20427,
 1.78854,
 1.57325,
 2.39786,
 4.12078,
 7.71376,
 8.02901,
 8.0098,
 10.3784,
 10.4525,
 8.94162,
 7.56588,
 7.22793,
 0.75917,
 0.44258,
 2.79177,
 3.671,
 11.092,
 9.50512,
 0.88875,
 2.22109,
 1.86889,
 6.51527,
 9.45209,
 9.19764,
 10.4886,
 12.0285,
 14.0491,
 16.154,
 19.1475,
 20.3197,
 20.8362,
 21.0598,
 18.9896,
 21.4569,
 18.8928,
 15.5625,
 11.3743,
 11.8405,
 13.0044,
 13.4276,
 10.1753,
 9.02657,
 7.43711,
 7.54912,
 6.1177,
 5.27818,
 4.84832,
 4.39771,
 4.23136,
 5.13848,
 6.0116,
 7.66261,
 7.64095,
 7.61929,
 7.72398,
 6.72569,
 7.88427,
 7.804,
 7.34912,
 3.87372,
 0.60667,
 1.3566,
 1.93362,
 3.33048,
 4.78946,
 2.99501,
 2.56981,
 2.55949,
 2.15058,
 3.17785,
 3.52171,
 4.20286,
 4.0976,
 5.06914,
 5.66384,
 9.08062,
 10.3468,
 11.2077,
 12.0094,
 11.7651,
 11.4791,
 11.8965,
 10.9123,
 10.7735,
 10.8866,
 10.8946,
 8.95376,
 8.76863,
 9.3903,
 7.94548,
 9.48519,
 8.42007,
 6.50201,
 3.12049,
 1.48294,
 2.06469,
 3.20588,
 3.0458,
 1.82803,
 6.42978,
 7.54296,
 8.52932,
 9.02401,
 8.93391,
 10.4066,
 13.1333,
 11.9641,
 12.0537,
 10.4302,
 10.2682,
 9.41735,
 9.34867,
 11.128,
 10.9933,
 9.7963,
 10.783,
 9.41297,
 8.62471,
 6.3227,
 3.80071,
 3.15205,
 3.93538,
 4.48113,
 5.35378,
 7.06128,
 7.21377,
 7.40772,
 7.93467,
 7.12934,
 6.95448,
 5.8524,
 2.90684,
 0.93804,
 0.4292,
 0.93031,
 0.72267,
 1.90048,
 2.3734,
 3.52301,
 4.80366,
 5.04275,
 3.08669,
 2.79477,
 1.82561,
 4.64077,
 6.8211,
 5.37181,
 6.79177,
 7.15537,
 7.42069,
 6.43159,
 6.39205,
 6.00971,
 6.26248,
 5.55757,
 5.30848,
 4.14295,
 2.65811,
 1.20915,
 2.05181,
 3.01101,
 3.77381,
 3.09387,
 4.33531,
 5.83912,
 5.58329,
 4.47558,
 4.51589,
 5.24705,
 5.47338,
 7.46482,
 8.20061,
 8.48305,
 8.31525,
 9.23903,
 10.3806,
 10.1807,
 10.7003,
 10.8078,
 8.55397,
 5.12402,
 2.67695,
 2.54574,
 3.61645,
 3.44266,
 4.00879,
 3.91392,
 2.63306,
 3.83902,
 3.80766,
 3.50758,
 4.26172,
 4.41638,
 4.77057,
 5.97767,
 8.06199,
 8.83247,
 8.88645,
 11.1098,
 12.4944,
 13.3821,
 11.1302,
 10.0084,
 8.49572,
 4.04637,
 3.88605,
 3.03146,
 1.40535,
 0.50579,
 1.70049,
 0.40666,
 0.06909,
 0.54029,
 1.89418,
 3.6114,
 3.45448,
 2.96756,
 2.56101,
 3.43753,
 5.16669,
 5.42433,
 7.58326,
 7.97668,
 9.12919,
 9.39669,
 8.86121,
 8.64495,
 6.73301,
 4.42145,
 6.04166,
 5.99725,
 6.23367,
 6.92635,
 7.09669,
 4.70875,
 3.21469,
 2.34367,
 3.55656,
 1.6119,
 2.83053,
 0.98607,
 1.3829,
 4.41446,
 8.7211,
 10.8782,
 9.77327,
 8.40942,
 7.33087,
 6.95716,
 7.84421,
 8.01107,
 7.13726,
 7.71554,
 6.64235,
 6.35497,
 3.66167,
 3.32151,
 3.95274,
 4.12361,
 3.31917,
 2.99481,
 2.87042,
 3.34698,
 3.333,
 4.23701,
 3.89337,
 4.75763,
 5.98796,
 10.0338,
 9.64799,
 10.1402,
 10.2759,
 9.36727,
 10.0261,
 9.473,
 9.19739,
 9.19835,
 7.61847,
 6.22211,
 6.04486,
 5.38679,
 5.69319,
 4.90067,
 4.92996,
 3.4959,
 3.35443,
 0.83124,
 5.28228,
 4.28683,
 4.13082,
 4.33157,
 7.18742,
 8.72384,
 8.77143,
 9.14385,
 10.6657,
 9.52622,
 9.65974,
 8.7975,
 8.27365,
 7.91926,
 7.35794,
 5.68898,
 6.40883,
 7.24364,
 5.53536,
 5.65704,
 6.05429,
 5.68336,
 6.84818,
 6.39795,
 6.97346,
 7.57118,
 7.99816,
 6.45322,
 6.76711,
 7.91559,
 7.94621,
 7.83153,
 7.38379,
 8.37265,
 7.5294,
 7.37235,
 7.86502,
 7.66575,
 7.83918,
 7.46338,
 8.69567,
 8.42419,
 8.5861,
 7.36267,
 8.05966,
 7.1686,
 6.28358,
 7.41863,
 7.14297,
 6.42924,
 5.95107,
 6.17059,
 7.36512,
 7.2081,
 6.75911,
 6.58145,
 6.81826,
 6.11369,
 6.13566,
 7.78254,
 7.53145,
 6.47905,
 5.67483,
 5.6991,
 5.64376,
 7.40188,
 7.46656,
 6.27451,
 4.61624,
 5.53485,
 5.44668,
 5.54346,
 5.87561,
 5.39868,
 5.22614,
 5.26491,
 6.74894,
 9.44863,
 8.62725,
 10.2554,
 9.1543,
 8.64118,
 7.92153,
 10.228,
 8.86206,
 8.63645,
 7.86515,
 7.3702,
 7.1986,
 9.01049,
 7.90418,
 7.76029,
 7.14643,
 7.13902,
 6.56206,
 6.52664,
 5.71724,
 3.74709,
 4.28585,
 7.18927,
 8.99824,
 9.6554,
 9.34622,
 10.3336,
 9.53414,
 10.4697,
 11.0639,
 12.1149,
 10.0131,
 9.2488,
 9.35354,
 8.98336,
 9.99151,
 8.97618,
 8.56135,
 8.04905,
 7.65675,
 9.91679,
 6.81184,
 7.84271,
 8.35798,
 9.58004,
 10.9771,
 11.7505,
 11.0432,
 11.8105,
 11.1634,
 10.1792,
 10.1003,
 9.14582,
 7.7145,
 7.56539,
 4.51149,
 1.96349,
 1.18428,
 4.14132,
 3.50985,
 3.79191,
 4.08572,
 6.5822,
 7.03902,
 5.23996,
 6.01652,
 6.10413,
 7.4473,
 6.37773,
 6.49095,
 7.31016,
 9.79174,
 9.004,
 10.1864,
 10.3356,
 10.3012,
 11.8033,
 10.4101,
 10.4459,
 9.75094,
 8.71072,
 9.77227,
 11.5351,
 11.6549,
 11.8198,
 9.31229,
 8.03621,
 8.3501,
 6.76208,
 6.51744,
 5.70593,
 5.0634,
 3.28122,
 3.07188,
 6.02651,
 5.50183,
 6.24642,
 7.27733,
 6.92378,
 6.46267,
 6.15615,
 5.20913,
 4.48779,
 5.74817,
 3.43444,
 2.33454,
 2.9469,
 2.96147,
 3.53564,
 2.59526,
 2.84438,
 2.35624,
 2.47745,
 3.10136,
 3.55773,
 3.90973,
 3.98191,
 4.24131,
 4.2413,
 5.14599,
 7.8851,
 11.0334,
 9.52816,
 9.60677,
 10.562,
 9.53616,
 9.02362,
 7.13393,
 6.82847,
 7.97923,
 7.75086,
 7.7559,
 8.0049,
 8.27067,
 7.91444,
 6.44292,
 6.66092,
 6.34095,
 5.76042,
 4.80872,
 5.90411,
 6.66397,
 8.26597,
 8.69112,
 10.7513,
 11.2168,
 10.8251,
 10.6585,
 11.4834,
 12.4807,
 ...]

In [98]:
# Computing minimum, maximum & mean

# Dummy values for min, max, sum

summ = 0
minn = 10000000000000000000000
maxx = -1

for i in range(0,col_len,1):
    if wspeed[i]<minn:
        minn = wspeed[i]
    if wspeed[i]>maxx:
        maxx = wspeed[i]
    
    summ = summ + wspeed[i]
    
avg = summ/col_len

print(minn,maxx,avg)
print(min(wspeed),max(wspeed),sum(wspeed)/col_len) # values check

# Computing standard deviation
# Formula - sqrt((sum(xi-avg)*(xi-avg))/N)

summm = 0
for i in range(0,col_len,1):
    summm = summm + (wspeed[i]-avg)*(wspeed[i]-avg)
    
std = mt.sqrt(summm/col_len)
print(std)
print(st.stdev(wspeed)) # values check

0.00795 21.4569 5.260611836187211
0.00795 21.4569 5.260611836187211
3.066946901934498 3.067005254948808

In [ ]:
# While loop - to compute the average ozone concentration when the temperature is greater than 70F.

In [100]:
# Extracting the dataframe for temperature > 70F

a2 = a.loc[(a['TEMP.ts'] > 70)]
a2.head()

# Extracting the ozone concentration as pandas series
oz = a2['OZONE.ts']
oz = list(oz) # converting to list

col_len = len(oz)

# converting the list elements to int

for i in range(0,col_len,1):
    oz[i] = float(oz[i])

oz

i = 0
summ = 0

while i < col_len:
    summ = summ + oz[i]
    i = i + 1

oz_avg = summ/col_len
print(oz_avg)

27.974868920207427

In [ ]:
# For loop - to compute the standard deviation of the ozone when temperature is > 70F AND NOX > 10 ppb

In [102]:
# Extracting the dataframe for temperature > 70F

a2 = a.loc[(a['TEMP.ts'] > 70) & (a['NOX.ts'] > 10)]
a2.head()

# Extracting the ozone concentration as pandas series
oz = a2['OZONE.ts']
oz = list(oz) # converting to list

col_len = len(oz)

# converting the list elements to int

for i in range(0,col_len,1):
    oz[i] = float(oz[i])

oz

i = 0
summ = 0

while i < col_len:
    summ = summ + oz[i]
    i = i + 1

oz_avg = summ/col_len

# Computing standard deviation
# Formula - sqrt((sum(xi-avg)*(xi-avg))/N)

summm = 0
for i in range(0,col_len,1):
    summm = summm + (oz[i]-oz_avg)*(oz[i]-oz_avg)
    
std = mt.sqrt(summm/col_len)
print(std)
print(st.stdev(oz)) # values check

14.04940903600119
14.051792513673098

In [ ]:
# To find the root of the equation (x-3) (x-5) = 3

In [117]:
tol = 1000000000000
init = 5
finit = 7

while tol > 1e-05:
    lhs = (init-3) * (init-5)
    rhs = 3
    tol = abs(lhs - rhs)
    init = init + 0.01
    
print("The root of the equation:",init)

The root of the equation: 6.0099999999999785